openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /spot/statistics:
    post:
      tags:
        - controller
      operationId: getPriceStatistics
      parameters:
        - name: caller
          in: header
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Statistic'
  /spot/historical:
    post:
      tags:
        - controller
      operationId: getHistoricalSpotPrice
      parameters:
        - name: caller
          in: header
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SpotPrice'
  /spot/historical/batch:
    post:
      tags:
        - controller
      operationId: getMultipleHistoricalSpotPrices
      parameters:
        - name: caller
          in: header
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SpotPrice'
  /spot/batch:
    post:
      tags:
        - controller
      operationId: getMultipleSpotPrices
      parameters:
        - name: caller
          in: header
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SpotPrice'
  /spot:
    post:
      tags:
        - controller
      operationId: getSpotPrice
      parameters:
        - name: caller
          in: header
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SpotPrice'
  /readyz:
    get:
      tags:
        - health-check-controller
      operationId: isReady
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /healthz:
    get:
      tags:
        - health-check-controller
      operationId: isAvailable
      parameters:
        - name: caller
          in: header
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    Request:
      required:
        - symbol
      type: object
      properties:
        symbol:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
    Statistic:
      type: object
      properties:
        symbol:
          type: string
        priceChange:
          type: string
        percentChange:
          type: string
        timeDelta:
          type: string
    SpotPrice:
      required:
        - base
      type: object
      properties:
        base:
          type: string
        currency:
          type: string
        amount:
          type: string
        date:
          type: string
          format: date
    BatchRequest:
      type: object
      properties:
        requests:
          maxItems: 5
          minItems: 2
          type: array
          items:
            $ref: '#/components/schemas/Request'
