apiVersion: apps/v1
kind: Deployment
metadata:
  name: econ-server-deployment
  labels:
    app: econ-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: econ-server
  template:
    metadata:
      labels:
        app: econ-server
    spec:
      containers:
        - name: econ-server
          image: briandidthat/econ-server
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              httpHeaders:
                - name: caller
                  value: kubernetes
            periodSeconds: 180
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: econ-server-service
spec:
  type: NodePort
  selector:
    app: econ-server
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
