apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-server
  labels:
    app: price-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-server
  template:
    metadata:
      labels:
        app: price-server
    spec:
      containers:
        - name: price-server
          image: briandidthat/price-server
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5


---
apiVersion: v1
kind: Service
metadata:
  name: price-server-service
spec:
  type: NodePort
  selector:
    app: price-server
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
