spring:
  application:
    name: price-server
  mvc:
    format:
      date: iso
      date-time: iso

server:
  port: 8080

apis:
  coinbase:
    baseUrl: https://api.coinbase.com/v2
  fred:
    baseUrl: https://api.stlouisfed.org/fred
    apiKey: ${FRED_API_KEY}